networks:
  default_network:
    driver: bridge

volumes:
  blib_local_postgres_data: {}
  blib_local_postgres_data_backups: {}
  blib_local_pgadmin_data: {}
  blib_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: blib_local_django
    container_name: blib_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - 8000:8000
    command: /start
    networks:
      - default_network

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: blib_production_postgres
    container_name: blib_production_postgres
    volumes:
      - blib_local_postgres_data:/var/lib/postgresql/data
      - blib_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - default_network

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: blib_local_pgadmin4
    depends_on:
      - postgres
    volumes:
      - blib_local_pgadmin_data:/var/lib/pgadmin
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - 8888:80
    networks:
      - default_network

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: blib_local_mailpit
    ports:
      - 8025:8025
    networks:
      - default_network

  redis:
    image: docker.io/redis:6
    container_name: blib_local_redis
    volumes:
      - blib_local_redis_data:/data
    networks:
      - default_network
    
  celeryworker:
    <<: *django
    image: blib_local_celeryworker
    container_name: blib_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker
    networks:
      - default_network

  celerybeat:
    <<: *django
    image: blib_local_celerybeat
    container_name: blib_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat
    networks:
      - default_network

  flower:
    <<: *django
    image: blib_local_flower
    container_name: blib_local_flower
    ports:
      - 5555:5555
    command: /start-flower
    networks:
      - default_network

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: blib_local_node
    container_name: blib_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - 3000:3000
    networks:
      - default_network
