# Generated by Django 4.2.14 on 2024-09-21 05:16

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=10, prefix='', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=55, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
                ('cover_image', models.ImageField(blank=True, upload_to='books/covers/')),
                ('public_url', models.URLField(blank=True, default='')),
                ('qr_code', models.ImageField(blank=True, upload_to='books/qr_codes/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
