# Generated by Django 4.2.14 on 2024-09-22 23:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=10, prefix='', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=55, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
                ('cover_image', models.ImageField(blank=True, upload_to='books/covers/')),
                ('public_url', models.URLField(blank=True, default='')),
                ('qr_code', models.ImageField(blank=True, upload_to='books/qr_codes/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'books',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='BookTagRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_tag_relationship', to='books.book')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.tag')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategoryRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_category_relationship', to='books.book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.category')),
            ],
        ),
    ]
