# Generated by Django 4.2.14 on 2024-10-05 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_bookauthorrelationship_remove_book_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='subscribed_categories', to='books.category')),
                ('subscribed_users', models.ManyToManyField(related_name='subscribed_users', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='subscribed_tags', to='books.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
