# Generated by Django 4.2.14 on 2024-11-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='subscribed_categories', to='books.category')),
            ],
        ),
    ]
