# Generated by Django 4.2.14 on 2024-11-04 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
        ('books', '0002_bookauthorrelationship_remove_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='subscribed_users',
            field=models.ManyToManyField(related_name='subscribed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='tags',
            field=models.ManyToManyField(related_name='subscribed_tags', to='books.tag'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
